# render.yaml
# Este es un archivo "Blueprint" de Render.
# Le dice a Render cómo construir y desplegar tu backend y frontend juntos.
# No necesitas cambiar nada aquí, pero SÍ necesitarás añadir tus variables
# secretas (claves de BBDD, AWS, etc.) en el panel de control de Render.

services:
  # ---------------- Backend Service (Python/FastAPI) ----------------
  - type: web
    name: inmo-backend
    env: python
    rootDir: backend
    plan: free # Puedes cambiar a 'starter' si necesitas más potencia
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      # La siguiente variable se inyecta automáticamente con la URL del frontend
      - key: FRONTEND_URL
        fromStaticSite:
          name: inmo-frontend # Apunta al sitio estático definido abajo
          property: url
      # --- ¡IMPORTANTE! Añade los siguientes valores en el Dashboard de Render ---
      - key: MONGO_URI
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: ADMIN_TOKEN
        sync: false

# ---------------- Frontend Service (React/Vite Static Site) ----------------
static_sites:
  - name: inmo-frontend
    env: node
    rootDir: frontend
    plan: free
    buildCommand: "npm install && npm run build"
    publishDir: dist # El directorio de salida de Vite
    envVars:
      # La siguiente variable se inyecta automáticamente con la URL del backend
      - key: VITE_API_URL
        fromService:
          type: web
          name: inmo-backend # Debe coincidir con el nombre del servicio de backend
          property: url